### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by kirsn** [iisc-sa-open/trsl#1]
I followed the instruction here: https://github.com/iisc-sa-open/trsl/wiki/testing-process to run the tests, and I see this:

```
d:\code\git\trsl>python tests\trsl_tests.py
Traceback (most recent call last):
  File "tests\trsl_tests.py", line 20, in <module>
    import trsl
ImportError: No module named trsl
```

If I run this from within Eclipse, then I see a different error:

```
Finding files... done.
Importing test modules ... done.

======================================================================
ERROR: test_leaf_word_probability (trsl_tests.TrslTestCase)
Validate if every leaf node has a word probability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/code/git/trsl/tests\trsl_tests.py", line 41, in setUp
    self.trsl_instance = trsl.Trsl(model=MODEL)
NameError: global name 'MODEL' is not defined

======================================================================
ERROR: test_probability_division (trsl_tests.TrslTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/code/git/trsl/tests\trsl_tests.py", line 41, in setUp
    self.trsl_instance = trsl.Trsl(model=MODEL)
NameError: global name 'MODEL' is not defined

======================================================================
ERROR: test_reduction (trsl_tests.TrslTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/code/git/trsl/tests\trsl_tests.py", line 41, in setUp
    self.trsl_instance = trsl.Trsl(model=MODEL)
NameError: global name 'MODEL' is not defined

======================================================================
ERROR: test_sample_size (trsl_tests.TrslTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/code/git/trsl/tests\trsl_tests.py", line 41, in setUp
    self.trsl_instance = trsl.Trsl(model=MODEL)
NameError: global name 'MODEL' is not defined

----------------------------------------------------------------------
Ran 4 tests in 0.007s

FAILED (errors=4)

```

**Comment by upman** [comment]
It seems to be expecting a command line argument that specifies a pre-built tree on which to run the tests.

**Comment by KshitijKarthick** [comment]
> Bug encountered after commit: cfe5db3bce6dad9959432de8eb5d270c17026df8,
 due to automatic organize of imports, trsl.py needs to be imported after setting the directory location. Commit 61de8a6f709b9716536280cd108a7dd25e9e4b41 fixes the same in trsl_tests.py, predict.py, tree_walk.py


> Secondly a pre-trained model needs to be passed, and the test is run over the model validating if the trsl construction was valid or not

 ```
$ python2 tests/trsl_tests.py --help
usage: trsl_tests.py [-h] -m MODEL

Test script for trsl.py

optional arguments:
  -h, --help                        show this help message and exit
  -m MODEL, --model MODEL           Model file path
```

> For example:
```
$ python2 tests/trsl_tests.py -m ./data.txt-model/model
```

The wiki will be updated to reflect the changes suitably
